name: Organization Secret Scan

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  org-wide-scan:
    uses: GlobalSignIn/.github/.github/workflows/secret-scan.yml@main
    secrets: inherit
